
# Application
spring.application.name=flowstock-pro


# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/flowstock_db
spring.datasource.username=srirakshagubbihal
spring.datasource.password=Sreeyathegreat1!

spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false