spring.application.name=flowstock-pro

spring.datasource.url=jdbc:postgresql://postgres:5432/flowstock_db
spring.datasource.username=flowstock
spring.datasource.password=flowstock_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false